apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-nfs
  name: nginx-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nfs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-nfs
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-data
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nfs-data
#spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 2Gi
#  storageClassName: nfs-sc
